--- #YAML:1.0
name:               Set-Relation
version:            0.12.5
abstract:           Relation data type for Perl
author:
    - Darren Duncan <perl@DarrenDuncan.net>
license:            lgpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.48
build_requires:
    Carp::Always:         0.09
    ExtUtils::MakeMaker:  6.48
    Test::Deep:           0.106
    Test::More:           0.92
requires:
    Class::MOP:           0.94
    List::MoreUtils:      0.22
    Moose:                0.92
    Moose::Role:          0.92
    namespace::autoclean:  0.09
    perl:                 5.8.1
    Scalar::Util:         1.21
resources:
    homepage:     http://www.muldis.com/
    license:      http://www.fsf.org/licensing/licenses/lgpl.html
    MailingList:  http://mm.DarrenDuncan.net/mailman/listinfo
    repository:   http://github.com/muldis/Set-Relation
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
