--- #YAML:1.0
name:                Set-Relation
version:             0.0.0
abstract:            Relation data type for Perl
license:             lgpl
author:              
    - Darren Duncan <perl@DarrenDuncan.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::MOP:                    0.75
    Moose:                         0.64
    version:                       0.74
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
