--- #YAML:1.0
name:               Set-Relation
version:            0.11.3
abstract:           Relation data type for Perl
author:
    - Darren Duncan <perl@DarrenDuncan.net>
license:            lgpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp::Always:         0.09
    Class::MOP:           0.89
    List::MoreUtils:      0.22
    Moose:                0.87
    Moose::Role:          0.87
    namespace::autoclean:  0.08
    Test::Deep:           0
    Test::More:           0.88
    version:              0.74
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.53_03
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
