--- #YAML:1.0
name:               Set-Relation
version:            0.12.3
abstract:           Relation data type for Perl
author:
    - Darren Duncan <perl@DarrenDuncan.net>
license:            lgpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp::Always:         0.09
    Class::MOP:           0.93
    List::MoreUtils:      0.22
    Moose:                0.9
    Moose::Role:          0.9
    namespace::autoclean:  0.09
    Test::Deep:           0.106
    Test::More:           0.92
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
