---
abstract: 'Relation data type for Perl'
author:
  - 'Darren Duncan <darren@DarrenDuncan.net>'
build_requires:
  Carp::Always: '0.01'
  ExtUtils::MakeMaker: '6.17'
  Test::Deep: '0.106'
  Test::More: '0.47'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Set-Relation
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '1.01'
  List::MoreUtils: '0.28'
  Scalar::Util: '1.13'
  perl: '5.008001'
resources:
  MailingList: http://mm.darrenduncan.net/mailman/listinfo
  homepage: http://www.muldis.com/
  license: http://www.fsf.org/licensing/licenses/lgpl.html
  repository: http://github.com/muldis/Set-Relation
version: v0.13.0
